
INSERT INTO threat_scenarios (title, description, type, severity, keywords, solution, mitigation_steps, explanation, usage_count, created_at, updated_at) VALUES
('Suspicious Email from Unknown Sender', 'You receive an email from an unknown sender asking you to click a link to verify your account.', 'phishing', 'low', '["suspicious", "email", "unknown", "sender", "verify", "account", "click", "link"]', 'Never click suspicious links. Always verify through official channels.', '["Do not click on any links in the email", "Verify the sender through official channels", "Check the email address for suspicious domains", "Report the email to your IT department", "Delete the email after reporting"]', 'This is a common phishing attempt where attackers try to steal your credentials by impersonating legitimate services.', 0, NOW(), NOW()),

('Fake IT Department Email', 'An email claiming to be from your IT department asks you to update your password by clicking a link.', 'phishing', 'medium', '["fake", "it", "department", "password", "update", "click", "link"]', 'Always verify IT requests through official channels.', '["Contact your IT department directly to verify", "Do not click the link", "Check the sender email address carefully", "Report to your security team", "Use official IT channels for password changes"]', 'Attackers often impersonate IT departments to gain access to employee credentials.', 0, NOW(), NOW()),

('Urgent Payment Request Scam', 'You receive an urgent email from what appears to be your supervisor requesting an immediate wire transfer.', 'phishing', 'high', '["urgent", "payment", "supervisor", "wire", "transfer", "immediate"]', 'Always verify payment requests through multiple channels.', '["Do not process any payment immediately", "Verify the request through phone call", "Check with your supervisor in person", "Follow your organization payment verification procedures", "Report to security team immediately"]', 'This is a business email compromise (BEC) attack targeting financial transactions.', 0, NOW(), NOW()),

('Social Media Friend Request Scam', 'You receive a friend request from someone claiming to be a coworker but the profile looks suspicious.', 'phishing', 'low', '["social", "media", "friend", "request", "coworker", "suspicious", "profile"]', 'Always verify social media connections through official channels.', '["Do not accept the friend request", "Verify the person identity in person", "Check if they already have a legitimate profile", "Report the fake profile to the platform", "Warn your colleagues about the suspicious account"]', 'Attackers create fake profiles to gather information about employees and their organizations.', 0, NOW(), NOW()),

('Fake Software License Renewal', 'You receive an email about renewing software licenses with a link to pay immediately.', 'phishing', 'medium', '["software", "license", "renewal", "pay", "immediately", "link"]', 'Verify all software renewals through official vendor channels.', '["Do not click payment links in emails", "Verify with your IT department", "Check official vendor websites directly", "Review your organization software inventory", "Report suspicious license renewal requests"]', 'Scammers impersonate software vendors to steal payment information and credentials.', 0, NOW(), NOW());


INSERT INTO threat_scenarios (title, description, type, severity, keywords, solution, mitigation_steps, explanation, usage_count, created_at, updated_at) VALUES
('Suspicious USB Drive Found', 'You find a USB drive in the parking lot labeled "Employee Salary Information - Confidential".', 'malware', 'high', '["usb", "drive", "found", "parking", "salary", "confidential"]', 'Never use unknown USB devices. Report to IT immediately.', '["Do not plug the USB drive into any computer", "Report the found device to security", "Turn in the device to your IT department", "Warn colleagues about the potential threat", "Follow your organization security protocols"]', 'USB drives found in public areas are often infected with malware as part of social engineering attacks.', 0, NOW(), NOW()),

('Suspicious Software Pop-up', 'A pop-up appears claiming your antivirus is out of date and needs immediate updating.', 'malware', 'medium', '["popup", "antivirus", "update", "software", "immediate"]', 'Only update software through official channels.', '["Do not click on the pop-up", "Close the browser or application", "Run a legitimate antivirus scan", "Update software through official channels only", "Report the incident to IT"]', 'Fake antivirus pop-ups are used to trick users into downloading malware.', 0, NOW(), NOW()),

('Computer Running Slowly', 'Your computer has been running unusually slow and showing strange pop-ups.', 'malware', 'medium', '["computer", "slow", "strange", "popup", "unusual"]', 'Isolate the system and run comprehensive security scans.', '["Disconnect from the network immediately", "Run a full system antivirus scan", "Contact IT support for assistance", "Do not access sensitive information", "Consider system restoration if needed"]', 'These symptoms often indicate malware infection affecting system performance.', 0, NOW(), NOW()),

('Infected Email Attachment', 'You accidentally opened a suspicious email attachment and now your computer is acting strange.', 'malware', 'high', '["infected", "email", "attachment", "suspicious", "computer", "strange"]', 'Immediately isolate and scan the system for threats.', '["Disconnect from the network immediately", "Do not use the infected system for sensitive tasks", "Contact IT department emergency line", "Run comprehensive malware scans", "Prepare for potential data recovery procedures"]', 'Email attachments are a common vector for malware distribution.', 0, NOW(), NOW()),

('Fake System Update', 'A notification appears claiming your operating system needs an urgent security update from an unofficial source.', 'malware', 'medium', '["fake", "system", "update", "operating", "urgent", "security", "unofficial"]', 'Only install updates through official system channels.', '["Do not install the update", "Close the notification", "Check for real updates through official channels", "Run a security scan", "Report the fake update notification"]', 'Fake system updates are used to install malware on unsuspecting users computers.', 0, NOW(), NOW());
